version: '3'
services:

  cms:
    image: ryannhg/wp-cms:latest
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: password
    links:
      - db:mysql

  db:
    image: ryannhg/wp-db:latest
    environment:
      MYSQL_ROOT_PASSWORD: password

  # web:
  #   build:
  #     context: ./web
  #     dockerfile: Dockerfile
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./web:/usr/src/app
  #   links:
  #     - cms:cms